FROM python:3.10.12-alpine

ENV HOME_APP=/home/app

RUN mkdir -p $HOME_APP

WORKDIR $HOME_APP

RUN pip install poetry==1.5.1

RUN poetry config virtualenvs.in-project true

EXPOSE 8000

CMD poetry install && poetry run python3 manage.py runserver 0.0.0.0:8000
