databases:
  - name: personal_website
    databaseName: personal_website
    user: personal_website

services:
  - type: web
    name: personal_website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn website.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personal_website
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 5
      - key: PYTHON_VERSION
        value: "3.8"
