# Generated by Django 4.2.2 on 2023-06-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=500)),
                ('position_name', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('img_src', models.CharField(max_length=700)),
                ('short_description', models.CharField(max_length=500)),
                ('show_in_landing', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
